# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_block_gibbs_sampler <- function(inits, block_inits, n) {
    .Call(`_telefit_test_block_gibbs_sampler`, inits, block_inits, n)
}

test_gibbs_sampler <- function(inits, nSamples) {
    .Call(`_telefit_test_gibbs_sampler`, inits, nSamples)
}

test_rw_sampler <- function(params, init, nSamples) {
    .Call(`_telefit_test_rw_sampler`, params, init, nSamples)
}

r_maternCov <- function(dist, scale, range, smoothness, nugget) {
    .Call(`_telefit_r_maternCov`, dist, scale, range, smoothness, nugget)
}

r_maternArray <- function(dist, scale, range, smoothness, nugget) {
    .Call(`_telefit_r_maternArray`, dist, scale, range, smoothness, nugget)
}

r_mc2_rinvwishart <- function(V, n) {
    .Call(`_telefit_r_mc2_rinvwishart`, V, n)
}

r_mvrnorm_postKron <- function(y, A, B, nSamples, precision) {
    .Call(`_telefit_r_mvrnorm_postKron`, y, A, B, nSamples, precision)
}

r_mvrnorm_post <- function(y, Sigma, nSamples, precision) {
    .Call(`_telefit_r_mvrnorm_post`, y, Sigma, nSamples, precision)
}

r_qintnorm <- function(breaks, mu, sigma) {
    .Call(`_telefit_r_qintnorm`, breaks, mu, sigma)
}

dtest <- function(x, m, n, k, R, q, ldetR, Sigma) {
    .Call(`_telefit_dtest`, x, m, n, k, R, q, ldetR, Sigma)
}

test_gaussian_approx_eta0 <- function(eta0, Q, it, beta, y, x, n, t, p) {
    .Call(`_telefit_test_gaussian_approx_eta0`, eta0, Q, it, beta, y, x, n, t, p)
}

test_gaussian_approx_beta <- function(beta0, Q, p, it, eta0, y, x, n, t) {
    .Call(`_telefit_test_gaussian_approx_beta`, beta0, Q, p, it, eta0, y, x, n, t)
}

test_taylor_beta <- function(beta0, eta0, y, x, n, t, p) {
    .Call(`_telefit_test_taylor_beta`, beta0, eta0, y, x, n, t, p)
}

test_taylor_eta0 <- function(beta, eta0, y, x, n, t, p) {
    .Call(`_telefit_test_taylor_eta0`, beta, eta0, y, x, n, t, p)
}

test_ll <- function(y, lambda) {
    .Call(`_telefit_test_ll`, y, lambda)
}

r_dgemkmm <- function(A, B, C) {
    .Call(`_telefit_r_dgemkmm`, A, B, C)
}

r_rwishart <- function(V, n) {
    .Call(`_telefit_r_rwishart`, V, n)
}

r_rinvwishart <- function(V, n) {
    .Call(`_telefit_r_rinvwishart`, V, n)
}

r_dgeikmm <- function(N, A, B) {
    .Call(`_telefit_r_dgeikmm`, N, A, B)
}

